openapi: 3.1.0
info:
  title: Storage
  version: 3.18.3
servers:
- url: https://api.tatum.io
paths:
  /v3/record:
    post:
      $ref: categories/storage/paths/v3_record_post.yml
    get:
      $ref: categories/storage/paths/v3_record_get.yml
  /v3/ipfs/{id}:
    get:
      $ref: categories/storage/paths/v3_ipfs_{id}_get.yml
  /v3/ipfs:
    post:
      $ref: categories/storage/paths/v3_ipfs_post.yml
